{{- if .Values.services.gotify.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.gotify.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.gotify.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.gotify.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.gotify.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.gotify.name }}
    spec:
      securityContext:
        fsGroup: {{ required "A valid GID required!" .Values.host.gid }}
      initContainers:
      {{- if .Values.services.gotify.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":8001"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
          volumeMounts:
            - name: wg0-conf
              mountPath: /gluetun/wireguard/
              readOnly: true
            - name: dev-net-tun
              mountPath: /dev/net/tun
        - name: verify-vpn
          image: busybox
          command:
            - sh
            - -c
            - |
              while ! ping -c 1 8.8.8.8; do
                echo "Ping failed, retrying in 5"
                sleep 5
              done
              echo "VPN connection established successfully, exiting"
      {{- end }}
      containers:
        - name: gotify
          image: "{{ .Values.services.gotify.image.repository }}:{{ .Values.services.gotify.image.tag }}"
          imagePullPolicy: {{ .Values.services.gotify.image.pullPolicy }}
          securityContext:
            runAsUser: {{ required "A valid UID required!" .Values.host.uid }}
            runAsGroup: {{ required "A valid GID required!" .Values.host.gid }}
            runAsNonRoot: true
          env:
            {{- range $key, $value := .Values.services.gotify.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: GOTIFY_DATABASE_DIALECT
              value: {{ .Values.services.gotify.databaseDialect }}
            - name: GOTIFY_DATABASE_CONNECTION
              value: {{ .Values.services.gotify.databaseConnection }}
            - name: GOTIFY_DEFAULTUSER_NAME
              value: {{ .Values.services.gotify.adminUsername }}
            - name: GOTIFY_DEFAULTUSER_PASS
              value: {{ .Values.services.gotify.adminPassword }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        {{- if .Values.services.gotify.vpn.enabled }}
        - name: wg0-conf
          secret:
            secretName: gluetun-wireguard-conf
            optional: false
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: data
          hostPath:
            path: "{{ .Values.services.gotify.data }}"
            type: Directory
{{- end }}
