{{- if .Values.services.gotify.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.gotify.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.gotify.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.gotify.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.gotify.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.gotify.name }}
    spec:
      securityContext:
        fsGroup: {{ required "A valid GID required!" .Values.host.gid }}
      initContainers:
      {{- if .Values.services.gotify.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-conf-secret
                optional: false
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: "127.0.0.1:9998"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: HEALTH_SERVER_ADDRESS
              value: "127.0.0.1:9999"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: {{ .Values.vpn.health.durationInitial | quote }}
            - name: HEALTH_VPN_DURATION_ADDITION
              value: {{ .Values.vpn.health.durationAddition | quote }}
            - name: HEALTH_SUCCESS_WAIT_DURATION
              value: {{ .Values.vpn.health.successWaitDuration | quote }}
            - name: HEALTH_TARGET_ADDRESS
              value: {{ .Values.vpn.health.targetAddress | quote }}
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 6
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
      {{- end }}
      containers:
        - name: gotify
          image: "{{ .Values.services.gotify.image.repository }}:{{ .Values.services.gotify.image.tag }}"
          imagePullPolicy: {{ .Values.services.gotify.image.pullPolicy }}
          securityContext:
            runAsUser: {{ required "A valid UID required!" .Values.host.uid }}
            runAsGroup: {{ required "A valid GID required!" .Values.host.gid }}
            runAsNonRoot: true
          env:
            {{- range $key, $value := .Values.services.gotify.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: GOTIFY_DATABASE_DIALECT
              value: {{ .Values.services.gotify.databaseDialect }}
            - name: GOTIFY_DATABASE_CONNECTION
              value: {{ .Values.services.gotify.databaseConnection }}
            - name: GOTIFY_DEFAULTUSER_NAME
              value: {{ .Values.services.gotify.adminUsername }}
            - name: GOTIFY_DEFAULTUSER_PASS
              value: {{ .Values.services.gotify.adminPassword }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        {{- if .Values.services.gotify.vpn.enabled }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: data
          hostPath:
            path: "{{ .Values.services.gotify.data }}"
            type: Directory
{{- end }}
