authentik:
    enabled: true
    secret_key: # REQUIRED; generate via `pwgen -s -B -n 50 1`
    error_reporting:
        enabled: false
    disable_update_check: false
    disable_startup_analytics: false
    postgresql:
        password: # REQUIRED; set the same value as in postgresql.auth.password
server:
    ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
            - "" # REQUIRED; MUST be set to 'authentik.<domain>.<tld>', e.g. 'authentik.example.com'
postgresql:
    enabled: true
    auth:
        password: # REQUIRED; generate via `pwgen -s -B -n 50 1`
redis:
    enabled: true
