apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: {{ .Values.certmanager.namespace }}
type: Opaque
stringData:
    api-token: {{ required "A valid .Values.certmanager.acme.dns01.cfApiToken required!" .Values.certmanager.acme.dns01.cfApiToken }}
