apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "A valid .Values.tls.acme.email required!" .Values.tls.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.tls.tlsSecretName }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
