{{- if .Values.services.plex.enabled }}
{{- $service := .Values.services.plex  }}
{{- $kind := "app" }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "homeserver.common.names.name" ( dict "service" $service "kind" $kind ) }}-remoteaccess"
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ $service.ports.remoteAccess }}
      nodePort: {{ $service.ports.remoteAccess }}
      targetPort: http
      protocol: TCP
  selector: {{- include "homeserver.common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
{{- end }}
