{{- if .Values.services.miniflux.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.miniflux.db.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.miniflux.db.name }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.miniflux.db.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.miniflux.db.name }}
    spec:
      containers:
        - name: miniflux-db
          image: postgres:17
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: {{ .Values.services.miniflux.db.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ required "A valid .Values.services.miniflux.db.password required!" .Values.services.miniflux.db.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.services.miniflux.db.dbname | quote }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.services.miniflux.db.user }}
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: data
          hostPath:
            path: "{{ .Values.services.miniflux.db.data }}"
            type: Directory
{{- end }}
