{{- if .Values.services.miniflux.enabled }}
{{- $service := .Values.services.miniflux  }}
{{- $kind := "app" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeserver.common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "homeserver.common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
{{- end }}
