{{- if .Values.services.backrest.enabled }}
{{- $service := .Values.services.backrest -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $service.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $service.name }}
        {{- include "homeserver.labels" . | indent 6 }}
        homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
    spec:
      securityContext:
        sysctls:
          {{- if $service.vpn.enabled }}
          {{- include "homeserver.vpn.wg-sysctls" . | indent 8 }}
          {{- end }}
      initContainers:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-sidecar" . | indent 6 }}
        {{- end }}
      containers:
        - name: backrest
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ $service.image.pullPolicy }}
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: BACKREST_DATA
              value: /data # path for backrest data. restic binary and the database are placed here.
            - name: BACKREST_CONFIG
              value: /config/config.json # path for the backrest config file.
            - name: XDG_CACHE_HOME
              value: /cache # path for the restic cache which greatly improves performance.
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
          volumeMounts:
            - name: userdata
              mountPath: /userdata
              readOnly: true
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
      volumes:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-volumes" . | indent 6 }}
        {{- end }}
        - name: userdata
          hostPath:
            path: "{{ $service.userdata }}"
            type: Directory
        - name: data
          hostPath:
            path: "{{ $service.data }}"
            type: Directory
        - name: config
          hostPath:
            path: "{{ $service.config }}"
            type: Directory
        - name: cache
          hostPath:
            path: "{{ $service.cache }}"
            type: Directory
{{- end }}
