{{- if .Values.services.whisparr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.whisparr.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.whisparr.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.whisparr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.whisparr.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.whisparr.name }}
    spec:
      initContainers:
      {{- if .Values.services.whisparr.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-conf-secret
                optional: false
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":9998"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: HEALTH_SERVER_ADDRESS
              value: ":9999"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: {{ .Values.vpn.health.durationInitial | quote }}
            - name: HEALTH_VPN_DURATION_ADDITION
              value: {{ .Values.vpn.health.durationAddition | quote }}
            - name: HEALTH_SUCCESS_WAIT_DURATION
              value: {{ .Values.vpn.health.successWaitDuration | quote }}
            - name: HEALTH_TARGET_ADDRESS
              value: {{ .Values.vpn.health.targetAddress | quote }}
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
            successThreshold: 1
      {{- end }}
      containers:
        - name: whisparr
          image: "{{ .Values.services.whisparr.image.repository }}:{{ .Values.services.whisparr.image.tag }}"
          imagePullPolicy: {{ .Values.services.whisparr.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.whisparr.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 6969
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: "{{ .Values.services.whisparr.data }}"
      volumes:
        {{- if .Values.services.whisparr.vpn.enabled }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: config
          hostPath:
            path: "{{ .Values.services.whisparr.config }}"
            type: Directory
        - name: data
          hostPath:
            path: "{{ .Values.services.whisparr.data }}"
            type: Directory
{{- end }}
