{{- if .Values.services.autobrr.enabled }}
{{- $service := .Values.services.autobrr -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: autobrr
    {{- include "homeserver.labels" . | indent 2 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $service.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: autobrr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autobrr
        {{- include "homeserver.labels" . | indent 6 }}
    spec:
      securityContext:
        fsGroup: {{ required "A valid GID required!" .Values.host.gid }}
      securityContext:
        sysctls:
          {{- if $service.vpn.enabled }}
          {{- include "homeserver.vpn.wg-sysctls" . | indent 8 }}
          {{- end }}
      initContainers:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-sidecar" . | indent 6 }}
        {{- end }}
      containers:
        - name: autobrr
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ $service.image.pullPolicy }}
          securityContext:
            runAsUser: {{ required "A valid UID required!" .Values.host.uid }}
            runAsGroup: {{ required "A valid GID required!" .Values.host.gid }}
            runAsNonRoot: true
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 7474
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-volumes" . | indent 6 }}
        {{- end }}
        - name: config
          hostPath:
            path: "{{ $service.config }}"
            type: Directory
{{- end }}
