{{- if .Values.services.autobrr.enabled }}
{{- $service := .Values.services.autobrr -}}
apiVersion: v1
kind: Service
metadata:
  name: autobrr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: autobrr
    {{- include "homeserver.labels" . | indent 2 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: autobrr
{{- end}}
