{{- if .Values.services.autobrr.enabled }}
{{- $service := .Values.services.autobrr  }}
{{- $kind := "app" }}
apiVersion: v1
kind: Service
metadata:
  name: autobrr
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
    app.kubernetes.io/name: autobrr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
    app.kubernetes.io/name: autobrr
{{- end}}
