{{- if .Values.services.kavita.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.kavita.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.kavita.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.kavita.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.services.kavita.name }}
{{- end }}
