{{- if .Values.services.huginn.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.services.huginn.db.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.huginn.db.name }}
spec:
  schedule: {{ .Values.services.huginn.db.backupScheduleCron }}
  timeZone: {{ required "A valid timezone required!" .Values.host.tz }}
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.huginn.db.name }}
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Values.services.huginn.db.name }}
        spec:
          containers:
            - name: huginn-db-backup
              image: postgres:17
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args:
                - -c
                - find /backup/ -mtime +{{ .Values.services.huginn.db.backupRetentionDays }} -exec rm -f {} \; ; pg_dump -Fc -C > /backup/huginn_db_backup_$(date +"%Y_%m_%d").dump
              env:
                - name: TZ
                  value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
                - name: PGHOST
                  value: {{ .Values.services.huginn.db.name | quote }}
                - name: PGUSER
                  value: {{ .Values.services.huginn.db.user | quote }}
                - name: PGPASSWORD
                  value: {{ required "A valid .Values.services.huginn.db.password required!" .Values.services.huginn.db.password | quote }}
                - name: PGDATABASE
                  value: {{ .Values.services.huginn.db.dbname | quote }}
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: backup
              hostPath:
                path: "{{ .Values.services.huginn.db.backup }}"
                type: Directory
          restartPolicy: OnFailure
{{- end }}
