{{- if .Values.services.huginn.enabled }}
{{- $service := .Values.services.huginn -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $service.name }}-db-backup-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}-db-backup-cronjob
    {{- include "homeserver.labels" . | indent 2 }}
spec:
  schedule: {{ $service.db.backupScheduleCron }}
  timeZone: {{ required "A valid timezone required!" .Values.host.tz }}
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $service.name }}-db-backup-cronjob
        {{- include "homeserver.labels" . | indent 6 }}
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ $service.name }}-db-backup-cronjob
            {{- include "homeserver.labels" . | indent 10 }}
        spec:
          containers:
            - name: huginn-db-backup
              image: postgres:17
              imagePullPolicy: Always
              command: ["/bin/sh"]
              args:
                - -c
                - find /backup/ -mtime +{{ $service.db.backupRetentionDays }} -exec rm -f {} \; ; pg_dump -Fc -C > /backup/huginn_db_backup_$(date +"%Y_%m_%d").dump
              env:
                - name: TZ
                  value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
                - name: PGHOST
                  value: {{ $service.db.name | quote }}
                - name: PGUSER
                  value: {{ $service.db.user | quote }}
                - name: PGPASSWORD
                  value: {{ required "A valid $service.db.password required!" $service.db.password | quote }}
                - name: PGDATABASE
                  value: {{ $service.db.dbname | quote }}
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: backup
              hostPath:
                path: "{{ $service.db.backup }}"
                type: Directory
          restartPolicy: OnFailure
{{- end }}
