{{- if .Values.services.huginn.enabled }}
{{- $service := .Values.services.huginn  }}
{{- $kind := "database" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: {{ $service.db.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ required "A valid $service.db.password required!" $service.db.password | quote }}
            - name: POSTGRES_DB
              value: {{ $service.db.dbName | quote }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          resources: {{- include "common.container.resources" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          volumeMounts: {{- include "common.container.volumeMounts" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ $service.db.user }}
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes: {{- include "common.pod.volumes" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
        - name: data
          hostPath:
            path: {{ $service.db.persistence.data | quote }}
            type: Directory
{{- end }}
