{{- if .Values.services.huginn.enabled }}
{{- $service := .Values.services.huginn  }}
{{- $kind := "database" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.db.ports.postgres }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector: {{- include "common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
{{- end }}
