{{- if .Values.services.huginn.enabled }}
{{- $service := .Values.services.huginn -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $service.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $service.name }}
        {{- include "homeserver.labels" . | indent 6 }}
        homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
    spec:
      # unfortunately the image needs root access
      # in order to write to the (root) /app directory
      securityContext:
        runAsNonRoot: false
      securityContext:
        sysctls:
          {{- if $service.vpn.enabled }}
          {{- include "homeserver.vpn.wg-sysctls" . | indent 8 }}
          {{- end }}
      initContainers:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-sidecar" . | indent 6 }}
        {{- end }}
      containers:
        - name: huginn
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ $service.image.pullPolicy }}
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: INVITATION_CODE
              value: {{ $service.invitationCode | quote }}
            - name: SKIP_INVITATION_CODE
            {{- if $service.invitationCode }}
              value: "false"
            {{- else }}
              value: "true"
            {{- end }}
            - name: REQUIRE_CONFIRMED_EMAIL
              value: "false"
            - name: APP_SECRET_TOKEN
              value: {{ required "A valid $service.appSecretToken required!" $service.appSecretToken | quote }}
            - name: DATABASE_ADAPTER
              value: postgresql
            - name: POSTGRES_PORT_5432_TCP_ADDR
              value: {{ $service.db.name | quote }}
            - name: POSTGRES_PORT_5432_TCP_PORT
              value: {{ $service.db.ports.postgres | quote }}
            - name: DATABASE_USERNAME
              value: {{ $service.db.user | quote }}
            - name: DATABASE_PASSWORD
              value: {{ required "A valid $service.db.password required!" $service.db.password | quote }}
            - name: DATABASE_NAME
              value: {{ $service.db.dbname | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
      volumes:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-volumes" . | indent 6 }}
        {{- end }}
{{- end }}
