{{- if .Values.services.changedetectionio.enabled }}
{{- $service := .Values.services.changedetectionio -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $service.name }}
{{- end }}
