{{- if .Values.services.kometa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.kometa.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.kometa.name }}
data:
  {{- range $path, $_ := .Files.Glob "files/kometa/**.yaml" }}
  {{- if not (contains "/default/" $path) }}
  {{ base $path }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
