{{- if .Values.services.kometa.enabled }}
{{- $service := .Values.services.kometa  }}
{{- $kind := "app" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/kometa/**.yaml" }}
  {{- if not (contains "/default/" $path) }}
  {{ base $path }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
