{{- if .Values.services.prowlarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.prowlarr.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.prowlarr.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.prowlarr.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.prowlarr.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.prowlarr.name }}
    spec:
      containers:
        - name: prowlarr
          image: "{{ .Values.services.prowlarr.image.repository }}:{{ .Values.services.prowlarr.image.tag }}"
          imagePullPolicy: {{ .Values.services.prowlarr.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.prowlarr.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: "{{ .Values.services.prowlarr.config }}"
            type: Directory
{{- end }}
