{{- if .Values.services.librechat.enabled }}
{{- $service := .Values.services.librechat  }}
{{- $kind := "database" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeserver.common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.db.ports.mongo }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector: {{- include "homeserver.common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
{{- end }}
