---
- Arr Stack:
      {{- if .Values.services.radarr.enabled }}
      - Radarr:
            icon: sh-radarr
            href: https://{{ .Values.services.radarr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.radarr.name }}:{{ .Values.services.radarr.ports.http }}
            description: Movies management
            widget:
                type: radarr
                url: http://{{ .Values.services.radarr.name }}:{{ .Values.services.radarr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.radarr.apiKey }}"
      {{- end }}
      {{- if .Values.services.sonarr.enabled }}
      - Sonarr:
            icon: sh-sonarr
            href: https://{{ .Values.services.sonarr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.sonarr.name }}:{{ .Values.services.sonarr.ports.http }}
            description: Series management
            widget:
                type: sonarr
                url: http://{{ .Values.services.sonarr.name }}:{{ .Values.services.sonarr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.sonarr.apiKey }}"
      {{- end }}
      {{- if .Values.services.lidarr.enabled }}
      - Lidarr:
            icon: sh-lidarr
            href: https://{{ .Values.services.lidarr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.lidarr.name }}:{{ .Values.services.lidarr.ports.http }}
            description: Music management
            widget:
                type: lidarr
                url: http://{{ .Values.services.lidarr.name }}:{{ .Values.services.lidarr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.lidarr.apiKey }}"
      {{- end }}
      {{- if .Values.services.whisparr.enabled }}
      - Whisparr:
            icon: https://raw.githubusercontent.com/Whisparr/Whisparr/refs/heads/develop/Logo/Whisparr.svg
            href: https://{{ .Values.services.whisparr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.whisparr.name }}:{{ .Values.services.whisparr.ports.http }}
            description: Adult videos management
      {{- end }}
      {{- if .Values.services.bazarr.enabled }}
      - Bazarr:
            icon: sh-bazarr
            href: https://{{ .Values.services.bazarr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.bazarr.name }}:{{ .Values.services.bazarr.ports.http }}
            description: Subtitles management
            widget:
                type: bazarr
                url: http://{{ .Values.services.bazarr.name }}:{{ .Values.services.bazarr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.bazarr.apiKey }}"
      {{- end }}
      {{- if .Values.services.autobrr.enabled }}
      - Autobrr:
            icon: sh-autobrr
            href: https://{{ .Values.services.autobrr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.autobrr.name }}:{{ .Values.services.autobrr.ports.http }}
            description: Download automation
            widget:
                type: autobrr
                url: http://{{ .Values.services.autobrr.name }}:{{ .Values.services.autobrr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.autobrr.apiKey }}"
      {{- end }}
      {{- if .Values.services.prowlarr.enabled }}
      - Prowlarr:
            icon: sh-prowlarr
            href: https://{{ .Values.services.prowlarr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.prowlarr.name }}:{{ .Values.services.prowlarr.ports.http }}
            description: Indexers management
            widget:
                type: prowlarr
                url: http://{{ .Values.services.prowlarr.name }}:{{ .Values.services.prowlarr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.prowlarr.apiKey }}"
      {{- end }}
- Downloaders:
      {{- if .Values.services.qbittorrent.enabled }}
      - qBittorrent:
            icon: sh-qbittorrent
            href: https://{{ .Values.services.qbittorrent.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.qbittorrent.name }}:{{ .Values.services.qbittorrent.ports.http }}
            description: Torrent downloader
            widget:
                type: qbittorrent
                url: http://{{ .Values.services.qbittorrent.name }}:{{ .Values.services.qbittorrent.ports.http }}
                fields: ["download", "upload"]
      {{- end }}
      {{- if .Values.services.sabnzbd.enabled }}
      - SABnzbd:
            icon: sh-sabnzbd
            href: https://{{ .Values.services.sabnzbd.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.sabnzbd.name }}:{{ .Values.services.sabnzbd.ports.http }}
            description: Usenet downloader
            widget:
                type: sabnzbd
                url: http://{{ .Values.services.sabnzbd.name }}:{{ .Values.services.sabnzbd.ports.http }}
                key: "{{ .Values.services.homepage.widgets.sabnzbd.apiKey }}"
      {{- end }}
      {{- if .Values.services.pinchflat.enabled }}
      - Pinchflat:
            icon: sh-pinchflat
            href: https://{{ .Values.services.pinchflat.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.pinchflat.name }}:{{ .Values.services.pinchflat.ports.http }}
            description: YouTube downloader
      {{- end }}
- Media:
      {{- if .Values.services.jellyseerr.enabled }}
      - Jellyseerr:
            icon: sh-jellyseerr
            href: https://{{ .Values.services.jellyseerr.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.jellyseerr.name }}:{{ .Values.services.jellyseerr.ports.http }}
            description: Request movies & series
            widget:
                type: jellyseerr
                url: http://{{ .Values.services.jellyseerr.name }}:{{ .Values.services.jellyseerr.ports.http }}
                key: "{{ .Values.services.homepage.widgets.jellyseerr.apiKey }}"
      {{- end }}
      {{- if .Values.services.plex.enabled }}
      - Plex:
            icon: sh-plex
            href: https://{{ .Values.services.plex.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.plex.name }}:{{ .Values.services.plex.ports.http }}
            description: Media server
            widget:
                type: tautulli
                url: http://{{ .Values.services.tautulli.name }}:{{ .Values.services.tautulli.ports.http }}
                key: "{{ .Values.services.homepage.widgets.tautulli.apiKey }}"
                enableUser: true # optional, defaults to false
                showEpisodeNumber: true # optional, defaults to false
                expandOneStreamToTwoRows: false # optional, defaults to true
      {{- end }}
      {{- if .Values.services.jellyfin.enabled }}
      - Jellyfin:
            icon: sh-jellyfin
            href: https://{{ .Values.services.jellyfin.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.jellyfin.name }}:{{ .Values.services.jellyfin.ports.http }}
            description: Media server
            widget:
                type: jellyfin
                url: http://{{ .Values.services.jellyfin.name }}:{{ .Values.services.jellyfin.ports.http }}
                key: "{{ .Values.services.homepage.widgets.jellyfin.apiKey }}"
                enableBlocks: true # optional, defaults to false
                enableNowPlaying: true # optional, defaults to true
                enableUser: false # optional, defaults to false
                showEpisodeNumber: true # optional, defaults to false
                expandOneStreamToTwoRows: false # optional, defaults to true
      {{- end }}
- Books:
      {{- if .Values.services.calibre.enabled }}
      - Calibre:
            icon: sh-calibre
            href: https://{{ .Values.services.calibre.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.calibre.name }}:{{ .Values.services.calibre.ports.http }}
            description: Book library
            widget:
                type: calibreweb
                url: http://{{ .Values.services.calibre.name }}:{{ .Values.services.calibre.ports.http }}
                username: "{{ .Values.services.homepage.widgets.calibre.username }}"
                password: "{{ .Values.services.homepage.widgets.calibre.password }}"
                fields: ["books", "authors", "series"]
      {{- end }}
      {{- if .Values.services.kavita.enabled }}
      - Kavita:
            icon: sh-kavita
            href: https://{{ .Values.services.kavita.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.kavita.name }}:{{ .Values.services.kavita.ports.http }}
            description: Book reader
            widget:
                type: kavita
                url: http://{{ .Values.services.kavita.name }}:{{ .Values.services.kavita.ports.http }}
                username: "{{ .Values.services.homepage.widgets.kavita.username }}"
                password: "{{ .Values.services.homepage.widgets.kavita.password }}"
      {{- end }}
      {{- if .Values.services.calibrebookdownloader.enabled }}
      - "Anna's Archive":
            icon: sh-calibre-web
            href: https://{{ .Values.services.calibrebookdownloader.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.calibrebookdownloader.name }}:{{ .Values.services.calibrebookdownloader.ports.http }}
            description: Download books from Anna's Archive
      {{- end }}
      {{- if .Values.services.openbooks.enabled }}
      - "IRCHighWay":
            icon: sh-openbooks
            href: https://{{ .Values.services.openbooks.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.openbooks.name }}:{{ .Values.services.openbooks.ports.http }}
            description: Download books from IRCHighWay
      {{- end }}
- Utilities:
      {{- if .Values.services.miniflux.enabled }}
      - RSS:
            icon: sh-miniflux-light
            href: https://{{ .Values.services.miniflux.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.miniflux.name }}:{{ .Values.services.miniflux.ports.http }}
            description: Feed reader
            widget:
                type: miniflux
                url: http://{{ .Values.services.miniflux.name }}:{{ .Values.services.miniflux.ports.http }}
                fields: ["unread"]
                key: "{{ .Values.services.homepage.widgets.miniflux.apiKey }}"
      {{- end }}
      {{- if .Values.services.thelounge.enabled }}
      - The Lounge:
            icon: https://raw.githubusercontent.com/thelounge/thelounge/master/client/img/logo-vertical-transparent-bg.svg?sanitize=true
            href: https://{{ .Values.services.thelounge.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.thelounge.name }}:{{ .Values.services.thelounge.ports.http }}
            description: IRC client
      {{- end }}
      {{- if .Values.services.convertx.enabled }}
      - Convertx:
            icon: sh-convertx
            href: https://{{ .Values.services.convertx.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.convertx.name }}:{{ .Values.services.convertx.ports.http }}
            description: File conversion
      {{- end }}
      {{- if .Values.services.stirlingpdf.enabled }}
      - Stirling PDF:
            icon: sh-stirling-pdf
            href: https://{{ .Values.services.stirlingpdf.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.stirlingpdf.name }}:{{ .Values.services.stirlingpdf.ports.http }}
            description: PDF Manipulation
      {{- end }}
      {{- if .Values.services.huginn.enabled }}
      - Huginn:
            icon: sh-huginn
            href: https://{{ .Values.services.huginn.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.huginn.name }}:{{ .Values.services.huginn.ports.http }}
            description: Monitors the world and acts on your behalf
      {{- end }}
      {{- if .Values.services.changedetectionio.enabled }}
      - Changedetection:
            icon: sh-changedetection
            href: https://{{ .Values.services.changedetectionio.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.changedetectionio.name }}:{{ .Values.services.changedetectionio.ports.http }}
            description: Website change detection
            widget:
                type: changedetectionio
                url: http://{{ .Values.services.changedetectionio.name }}:{{ .Values.services.changedetectionio.ports.http }}
                key: "{{ .Values.services.homepage.widgets.changedetection.apiKey }}"
      {{- end }}
      {{- if .Values.services.archivebox.enabled }}
      - Archivebox:
            icon: sh-archivebox
            href: https://{{ .Values.services.archivebox.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.archivebox.name }}:{{ .Values.services.archivebox.ports.http }}
            description: Web archiving
      {{- end }}
      {{- if .Values.services.apprise.enabled }}
      - Apprise:
            icon: sh-apprise
            href: https://{{ .Values.services.apprise.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.apprise.name }}:{{ .Values.services.apprise.ports.http }}
            description: Send notifications to any service
      {{- end }}
      {{- if .Values.services.gotify.enabled }}
      - Gotify:
            icon: sh-gotify
            href: https://{{ .Values.services.gotify.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.gotify.name }}:{{ .Values.services.gotify.ports.http }}
            description: Push notifications
            widget:
                type: gotify
                url: http://{{ .Values.services.gotify.name }}:{{ .Values.services.gotify.ports.http }}
                key: "{{ .Values.services.homepage.widgets.gotify.apiKey }}"
      {{- end }}
- Monitoring:
      {{- if .Values.services.myspeed.enabled }}
      - MySpeed:
            icon: sh-myspeed
            href: https://{{ .Values.services.myspeed.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.myspeed.name }}:{{ .Values.services.myspeed.ports.http }}
            description: Internet speed tracker
            widget:
                type: myspeed
                url: http://{{ .Values.services.myspeed.name }}:{{ .Values.services.myspeed.ports.http }}
      {{- end }}
      - Authentik:
            icon: sh-authentik
            href: https://authentik.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: https://authentik.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            description: SSO authentication
            widget:
                type: authentik
                url: http://authentik-server.{{ .Values.authentik.namespace }}.svc.cluster.local:80
                key: "{{ .Values.services.homepage.widgets.authentik.apiKey }}"
      {{- if .Values.services.backrest.enabled }}
      - Backrest:
            icon: sh-backrest-light
            href: https://{{ .Values.services.backrest.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}
            siteMonitor: http://{{ .Values.services.backrest.name }}:{{ .Values.services.backrest.ports.http }}
            description: Backups management
      {{- end }}
