{{- if .Values.services.calibrebookdownloader.enabled }}
{{- $service := .Values.services.calibrebookdownloader -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $service.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $service.name }}
        {{- include "homeserver.labels" . | indent 6 }}
        homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
    spec:
      securityContext:
        sysctls:
          {{- if $service.vpn.enabled }}
          {{- include "homeserver.vpn.wg-sysctls" . | indent 8 }}
          {{- end }}
      initContainers:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-sidecar" . | indent 6 }}
        {{- end }}
      containers:
        {{- if $service.useCfBypass }}
        - name: cloudflarebypassforscraping
          image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
        {{- end }}
        - name: calibrebookdownloader
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ $service.image.pullPolicy }}
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: UID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: GID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: FLASK_PORT
              value: "8084"
            - name: FLASK_DEBUG
              value: "false"
            - name: USE_CF_BYPASS
              value: {{ $service.useCfBypass | quote }}
            {{- if $service.useCfBypass }}
            - name: CLOUDFLARE_PROXY_URL
              value: http://localhost:8000
            {{- end }}
            - name: INGEST_DIR
              value: /cwa-book-ingest
            - name: BOOK_LANGUAGE
              value: {{ $service.bookLanguage }}
            - name: SUPPORTED_FORMATS
              value: {{ $service.supportedFormats }}
            {{- if $service.annasArchiveDonatorKey }}
            - name: AA_DONATOR_KEY
              value: {{ $service.annasArchiveDonatorKey }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          volumeMounts:
            - name: ingest
              mountPath: /cwa-book-ingest
      volumes:
        {{- if $service.vpn.enabled }}
        {{- include "homeserver.vpn.wg-volumes" . | indent 6 }}
        {{- end }}
        - name: ingest
          hostPath:
            path: "{{ .Values.services.calibre.ingest }}"
            type: Directory
{{- end }}
