{{- if .Values.services.calibrebookdownloader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.calibrebookdownloader.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.calibrebookdownloader.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.calibrebookdownloader.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.calibrebookdownloader.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.calibrebookdownloader.name }}
    spec:
      initContainers:
      {{- if .Values.services.calibrebookdownloader.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-conf-secret
                optional: false
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":9998"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: HEALTH_SERVER_ADDRESS
              value: ":9999"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: {{ .Values.vpn.health.durationInitial | quote }}
            - name: HEALTH_VPN_DURATION_ADDITION
              value: {{ .Values.vpn.health.durationAddition | quote }}
            - name: HEALTH_SUCCESS_WAIT_DURATION
              value: {{ .Values.vpn.health.successWaitDuration | quote }}
            - name: HEALTH_TARGET_ADDRESS
              value: {{ .Values.vpn.health.targetAddress | quote }}
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
            successThreshold: 1
      {{- end }}
      containers:
        {{- if .Values.services.calibrebookdownloader.useCfBypass }}
        - name: cloudflarebypassforscraping
          image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
        {{- end }}
        - name: calibrebookdownloader
          image: "{{ .Values.services.calibrebookdownloader.image.repository }}:{{ .Values.services.calibrebookdownloader.image.tag }}"
          imagePullPolicy: {{ .Values.services.calibrebookdownloader.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.calibrebookdownloader.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: UID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: GID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: FLASK_PORT
              value: "8084"
            - name: FLASK_DEBUG
              value: "false"
            - name: USE_CF_BYPASS
              value: {{ .Values.services.calibrebookdownloader.useCfBypass | quote }}
            {{- if .Values.services.calibrebookdownloader.useCfBypass }}
            - name: CLOUDFLARE_PROXY_URL
              value: http://localhost:8000
            {{- end }}
            - name: INGEST_DIR
              value: /cwa-book-ingest
            - name: BOOK_LANGUAGE
              value: {{ .Values.services.calibrebookdownloader.bookLanguage }}
            - name: SUPPORTED_FORMATS
              value: {{ .Values.services.calibrebookdownloader.supportedFormats }}
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          volumeMounts:
            - name: ingest
              mountPath: /cwa-book-ingest
      volumes:
        {{- if .Values.services.calibrebookdownloader.vpn.enabled }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: ingest
          hostPath:
            path: "{{ .Values.services.calibre.ingest }}"
            type: Directory
{{- end }}
