{{- if .Values.services.playwright.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.playwright.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.playwright.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.playwright.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.playwright.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.playwright.name }}
    spec:
      containers:
        - name: playwright
          image: "{{ .Values.services.playwright.image.repository }}:{{ .Values.services.playwright.image.tag }}"
          imagePullPolicy: {{ .Values.services.playwright.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.playwright.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: TOKEN
              value: {{ required "A valid .Values.services.playwright.token required!" .Values.services.playwright.token | quote }}
            - name: TIMEOUT
              value: {{ .Values.services.playwright.timeout | quote }}
            - name: CONCURRENT
              value: {{ .Values.services.playwright.maxConcurrentSessions | quote }}
            - name: QUEUED
              value: {{ .Values.services.playwright.maxQueueLength | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.services.playwright.config | quote }}
            type: Directory
{{- end }}
