{{- if .Values.services.qbittorrent.enabled }}
{{- $service := .Values.services.qbittorrent  }}
{{- $kind := "app" }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "homeserver.common.names.name" ( dict "service" $service "kind" $kind ) }}-active-p2p"
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  type: NodePort
  selector:
  ports:
    - name: p2p
      port: {{ $service.ports.p2p }}
      nodePort: {{ $service.ports.p2p }}
      targetPort: p2p
      protocol: TCP
    - name: p2pudp
      port: {{ $service.ports.p2p }}
      nodePort: {{ $service.ports.p2p }}
      targetPort: p2pudp
      protocol: UDP
{{- end }}
