{{- if .Values.services.qbittorrent.enabled }}
{{- $service := .Values.services.qbittorrent  }}
{{- $kind := "app" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeserver.common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "homeserver.common.names.namespace" . | quote }}
  labels: {{- include "homeserver.common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
  annotations: {{- include "homeserver.common.annotations.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "homeserver.common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
{{- end }}
