apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ printf "%s-high-priority" (include "common.names.namespace" .) | quote }}
  labels: {{- include "common.labels.standard" ( dict "context" $ ) | nindent 4 }}
value: 1000000
globalDefault: false
description: "This priority class should be used for high priority homeserver services only"
