{{- if .Values.services.sabnzbd.enabled }}
{{- $service := .Values.services.sabnzbd  }}
{{- $kind := "app" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/sabnzbd/scripts/**.py" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
{{- end }}
