{{- if .Values.services.sabnzbd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.sabnzbd.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.sabnzbd.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.sabnzbd.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.sabnzbd.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.sabnzbd.name }}
      annotations:
        checksum/config-scripts: {{ include (print $.Template.BasePath "/apps/sabnzbd/scripts-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      {{- if .Values.services.sabnzbd.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":8001"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
          volumeMounts:
            - name: wg0-conf
              mountPath: /gluetun/wireguard/
              readOnly: true
            - name: dev-net-tun
              mountPath: /dev/net/tun
        - name: verify-vpn
          image: busybox
          command:
            - sh
            - -c
            - |
              while ! ping -c 1 8.8.8.8; do
                echo "Ping failed, retrying in 5"
                sleep 5
              done
              echo "VPN connection established successfully, exiting"
      {{- end }}
        - name: host-whitelist
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - sed -i "s/host_whitelist\s*=.*/host_whitelist = {{ .Values.services.sabnzbd.name }},{{ .Values.services.sabnzbd.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}/" /config/sabnzbd.ini
          volumeMounts:
            - name: config
              mountPath: /config
        - name: add-scripts
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - mkdir -p /config/scripts && cp -rfL /tmp/scripts/* /config/scripts/ && chmod -R a=,a+rx,u+w,g+w /config/scripts
          volumeMounts:
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /tmp/scripts
      containers:
        - name: sabnzbd
          image: "{{ .Values.services.sabnzbd.image.repository }}:{{ .Values.services.sabnzbd.image.tag }}"
          imagePullPolicy: {{ .Values.services.sabnzbd.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.sabnzbd.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: {{ .Values.services.sabnzbd.data | quote }}
      volumes:
        {{- if .Values.services.sabnzbd.vpn.enabled }}
        - name: wg0-conf
          secret:
            secretName: gluetun-wireguard-conf
            optional: false
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: scripts
          configMap:
            name: "{{ .Values.services.sabnzbd.name }}-scripts"
        - name: config
          hostPath:
            path: {{ .Values.services.sabnzbd.config | quote }}
            type: Directory
        - name: data
          hostPath:
            path: {{ .Values.services.sabnzbd.data | quote }}
            type: Directory
{{- end }}
