{{- if .Values.services.sabnzbd.enabled }}
{{- $service := .Values.services.sabnzbd -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $service.name }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
data:
  {{- range $path, $_ := .Files.Glob "files/sabnzbd/scripts/**.py" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
{{- end }}
