{{- if .Values.services.sabnzbd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.sabnzbd.name }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.sabnzbd.name }}
data:
  {{- range $path, $_ := .Files.Glob "files/sabnzbd/scripts/**.py" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
{{- end }}
