{{- if .Values.services.archivebox.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.archivebox.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.archivebox.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.archivebox.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.archivebox.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.archivebox.name }}
    spec:
      initContainers:
      {{- if .Values.services.archivebox.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-conf-secret
                optional: false
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: "127.0.0.1:9998"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: HEALTH_SERVER_ADDRESS
              value: "127.0.0.1:9999"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: {{ .Values.vpn.health.durationInitial | quote }}
            - name: HEALTH_VPN_DURATION_ADDITION
              value: {{ .Values.vpn.health.durationAddition | quote }}
            - name: HEALTH_SUCCESS_WAIT_DURATION
              value: {{ .Values.vpn.health.successWaitDuration | quote }}
            - name: HEALTH_TARGET_ADDRESS
              value: {{ .Values.vpn.health.targetAddress | quote }}
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 6
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
      {{- end }}
      containers:
        - name: archivebox
          image: "{{ .Values.services.archivebox.image.repository }}:{{ .Values.services.archivebox.image.tag }}"
          imagePullPolicy: {{ .Values.services.archivebox.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.archivebox.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: ADMIN_USERNAME
              value: {{ .Values.services.archivebox.adminUsername | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.services.archivebox.adminPassword | quote }}
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://{{ .Values.services.archivebox.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
            - name: ALLOWED_HOSTS
              value: "{{ .Values.services.archivebox.name }},{{ .Values.services.archivebox.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
            - name: REVERSE_PROXY_USER_HEADER
              value: "X-authentik-email"
            - name: REVERSE_PROXY_WHITELIST
              value: "10.42.0.0/15"
            - name: PUBLIC_INDEX
              value: "false"
            - name: PUBLIC_SNAPSHOTS
              value: "false"
            - name: PUBLIC_ADD_VIEW
              value: "false"
            - name: SAVE_TITLE
              value: {{ .Values.services.archivebox.saveTitle | quote }}
            - name: SAVE_FAVICON
              value: {{ .Values.services.archivebox.saveFavicon | quote }}
            - name: SAVE_WGET
              value: {{ .Values.services.archivebox.saveWget | quote }}
            - name: SAVE_WARC
              value: {{ .Values.services.archivebox.saveWarc | quote }}
            - name: SAVE_PDF
              value: {{ .Values.services.archivebox.savePdf | quote }}
            - name: SAVE_SCREENSHOT
              value: {{ .Values.services.archivebox.saveScreenshot | quote }}
            - name: SAVE_DOM
              value: {{ .Values.services.archivebox.saveDom | quote }}
            - name: SAVE_SINGLEFILE
              value: {{ .Values.services.archivebox.saveSinglefile | quote }}
            - name: SAVE_READABILITY
              value: {{ .Values.services.archivebox.saveReadability | quote }}
            - name: SAVE_MERCURY
              value: {{ .Values.services.archivebox.saveMercury | quote }}
            - name: SAVE_GIT
              value: {{ .Values.services.archivebox.saveGit | quote }}
            - name: SAVE_MEDIA
              value: {{ .Values.services.archivebox.saveMedia | quote }}
            - name: SAVE_ARCHIVE_DOT_ORG
              value: {{ .Values.services.archivebox.saveArchiveDotOrg | quote }}
            - name: MEDIA_MAX_SIZE
              value: {{ .Values.services.archivebox.mediaMaxSize | quote }}
            - name: TIMEOUT
              value: {{ .Values.services.archivebox.timeout | quote }}
            - name: CHECK_SSL_VALIDITY
              value: "true"
            - name: WGET_USER_AGENT
              value: {{ .Values.services.archivebox.userAgent | quote }}
            - name: CURL_USER_AGENT
              value: {{ .Values.services.archivebox.userAgent | quote }}
            - name: CHROME_USER_AGENT
              value: {{ .Values.services.archivebox.userAgent | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        {{- if .Values.services.archivebox.vpn.enabled }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: data
          hostPath:
            path: "{{ .Values.services.archivebox.data }}"
            type: Directory
{{- end }}
