{{- if .Values.services.openbooks.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.openbooks.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.openbooks.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.openbooks.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.openbooks.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.openbooks.name }}
    spec:
      initContainers:
      {{- if .Values.services.openbooks.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":8001"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
          volumeMounts:
            - name: wg0-conf
              mountPath: /gluetun/wireguard/
              readOnly: true
            - name: dev-net-tun
              mountPath: /dev/net/tun
        - name: verify-vpn
          image: busybox
          command:
            - sh
            - -c
            - |
              while ! ping -c 1 8.8.8.8; do
                echo "Ping failed, retrying in 5"
                sleep 5
              done
              echo "VPN connection established successfully, exiting"
      {{- end }}
      containers:
        - name: openbooks
          image: "{{ .Values.services.openbooks.image.repository }}:{{ .Values.services.openbooks.image.tag }}"
          args:
            - --persist
            - --name
            - "{{ required "A valid IRC name required!" .Values.services.openbooks.ircname }}"
            - --no-browser-downloads
            - "{{ .Values.services.openbooks.noBrowserDownloads }}"
            - --tls
            - "true"
          imagePullPolicy: {{ .Values.services.openbooks.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.openbooks.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: ingest
              mountPath: /books/books # see https://github.com/evan-buss/openbooks/issues/60
      volumes:
        {{- if .Values.services.openbooks.vpn.enabled }}
        - name: wg0-conf
          secret:
            secretName: gluetun-wireguard-conf
            optional: false
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: ingest
          hostPath:
            path: "{{ .Values.services.calibre.ingest }}"
            type: Directory
{{- end }}
