{{- if .Values.services.apprise.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.apprise.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.apprise.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.apprise.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.apprise.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.apprise.name }}
    spec:
      securityContext:
        fsGroup: {{ required "A valid GID required!" .Values.host.gid }}
      containers:
        - name: apprise
          image: "{{ .Values.services.apprise.image.repository }}:{{ .Values.services.apprise.image.tag }}"
          imagePullPolicy: {{ .Values.services.apprise.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.apprise.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.services.apprise.logLevel | quote }}
            - name: APPRISE_STATEFUL_MODE
              value: {{ .Values.services.apprise.statefulMode | quote }}
            - name: APPRISE_ATTACH_SIZE
              value: {{ .Values.services.apprise.attachSizeMegabytes | quote }}
            - name: APPRISE_DEFAULT_THEME
              value: {{ .Values.services.apprise.defaultTheme | quote }}
            - name: APPRISE_DEFAULT_CONFIG_ID
              value: {{ .Values.services.apprise.defaultConfigId | quote }}
            - name: ALLOWED_HOSTS
              value: "{{ .Values.services.apprise.name }}.{{ required "A valid .Values.ingress.domain required!" .Values.ingress.domain }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: attachments
              mountPath: /attachments
      volumes:
        - name: config
          hostPath:
            path: "{{ .Values.services.apprise.config }}"
            type: Directory
        - name: attachments
          emptyDir: {}
{{- end }}
