{{- if .Values.services.mealie.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mealie
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.mealie.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mealie
{{- end}}
