{{- if .Values.services.calibrebookdownloader.enabled }}
{{- $service := .Values.services.calibrebookdownloader  }}
{{- $kind := "app" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $service.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ include "common.pod.automountServiceAccountToken" (dict "service" $service "kind" $kind "context" $) }}
      enableServiceLinks: {{ include "common.pod.enableServiceLinks" (dict "service" $service "kind" $kind "context" $) }}
      priorityClassName: {{ include "common.pod.priorityClass" (dict "service" $service "kind" $kind "context" $) | quote }}
      securityContext: {{- include "common.pod.securityContext" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
      initContainers: {{- include "common.pod.initContainers" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
        {{- include "common.initContainer.volumePermissions" ( dict "volumes" (list "ingest") "context" $ ) | nindent 8 }}
      containers:
        {{- if $service.useCfBypass }}
        - name: cloudflarebypassforscraping
          image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
        {{- end }}
        - name: calibre-book-downloader
          image: {{ printf "%s:%s" $service.image.repository $service.image.tag | quote }}
          imagePullPolicy: {{ $service.image.pullPolicy }}
          securityContext: {{- include "common.container.securityContext" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          envFrom: {{- include "common.container.envFrom" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          env: {{- include "common.container.env" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
            - name: UID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: GID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: FLASK_PORT
              value: "8084"
            - name: FLASK_DEBUG
              value: "false"
            - name: USE_CF_BYPASS
              value: {{ $service.useCfBypass | quote }}
            {{- if $service.useCfBypass }}
            - name: CLOUDFLARE_PROXY_URL
              value: http://localhost:8000
            {{- end }}
            - name: INGEST_DIR
              value: /cwa-book-ingest
            - name: BOOK_LANGUAGE
              value: {{ $service.bookLanguage }}
            - name: SUPPORTED_FORMATS
              value: {{ $service.supportedFormats }}
            {{- if $service.annasArchiveDonatorKey }}
            - name: AA_DONATOR_KEY
              value: {{ $service.annasArchiveDonatorKey }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          resources: {{- include "common.container.resources" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          volumeMounts: {{- include "common.container.volumeMounts" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
            - name: ingest
              mountPath: /cwa-book-ingest
      volumes: {{- include "common.pod.volumes" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
        - name: ingest
          hostPath:
            path: {{ .Values.services.calibre.persistence.ingest | quote }}
            type: Directory
{{- end }}
