{{- if .Values.services.homepage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.services.homepage.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.homepage.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups: # see https://github.com/gethomepage/homepage/pull/2003
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.services.homepage.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.homepage.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.services.homepage.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.services.homepage.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
