{{- if .Values.services.homepage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.homepage.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.homepage.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.homepage.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.homepage.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.homepage.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apps/homepage/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.services.homepage.name }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        fsGroup: {{ required "A valid GID required!" .Values.host.gid }}
      initContainers:
      {{- if .Values.services.homepage.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":8001"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: WIREGUARD_MTU
              value: "1320"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: "60s"
            - name: HEALTH_SUCCESS_WAIT_DURATION
              value: "30s"
          volumeMounts:
            - name: wg0-conf
              mountPath: /gluetun/wireguard/
              readOnly: true
            - name: dev-net-tun
              mountPath: /dev/net/tun
        - name: verify-vpn
          image: busybox
          command:
            - sh
            - -c
            - |
              tries=0
              while ! ping -c 1 8.8.8.8; do
                tries=$((tries+1))
                if [ $tries -eq 12 ]; then
                  echo "Timeout limit exceeded, couldn't establish VPN connection"
                  exit 1
                fi
                echo "Ping failed, retrying in 5s"
                sleep 5
              done
              echo "VPN connection established successfully"
      {{- end }}
        - name: add-homepage-config
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - cp -rfL /tmp/config/* /app/config/ && chmod -R a=,a+rX,u+w,g+w /app/config
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: homepage-config
              mountPath: /tmp/config
      containers:
        - name: homepage
          image: "{{ .Values.services.homepage.image.repository }}:{{ .Values.services.homepage.image.tag }}"
          imagePullPolicy: {{ .Values.services.homepage.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.homepage.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        {{- if .Values.services.homepage.vpn.enabled }}
        - name: wg0-conf
          secret:
            secretName: gluetun-wireguard-conf
            optional: false
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: homepage-config
          configMap:
            name: {{ .Values.services.homepage.name }}
        - name: config
          emptyDir: {}
{{- end }}
