{{- if .Values.services.homepage.enabled }}
{{- $service := .Values.services.homepage  }}
{{- $kind := "app" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ $service.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "service" $service "kind" $kind "context" $ ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "service" $service "kind" $kind "context" $ ) | nindent 8 }}
      annotations:
        checksum/config: {{ include "common.utils.checksumTemplate" ( dict "path" "/apps/homepage/configmap.yaml" "context" $ ) }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      priorityClassName: {{ include "common.pod.priorityClass" (dict "service" $service "kind" $kind "context" $) | quote }}
      serviceAccountName: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
      dnsPolicy: ClusterFirst
      securityContext: {{- include "common.pod.securityContext" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
      initContainers: {{- include "common.pod.initContainers" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
        {{- include "common.initContainer.volumePermissions" ( dict "volumes" (list) "context" $ ) | nindent 8 }}
        - name: init-homepage-config
          image: {{ include "common.initContainer.utility-image" . | quote }}
          imagePullPolicy: IfNotPresent
          securityContext: {{- include "common.container.securityContext" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          command:
            - /bin/sh
            - -ec
            - |-
              cp -rfL /tmp/config/* /app/config/
          resources: {{- include "common.resources.preset" (dict "type" "nano") | nindent 12 }}
          volumeMounts:
            - name: empty-dir
              mountPath: /app/config
              subPath: app-config-dir
            - name: homepage-config
              mountPath: /tmp/config
      containers:
        - name: homepage
          image: {{ printf "%s:%s" $service.image.repository $service.image.tag | quote }}
          imagePullPolicy: {{ $service.image.pullPolicy }}
          securityContext: {{- include "common.container.securityContext" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          envFrom: {{- include "common.container.envFrom" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          env: {{- include "common.container.env" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: {{- include "common.container.resources" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
          volumeMounts: {{- include "common.container.volumeMounts" (dict "service" $service "kind" $kind "context" $) | nindent 12 }}
            - name: empty-dir
              mountPath: /app/config
              subPath: app-config-dir
      volumes: {{- include "common.pod.volumes" (dict "service" $service "kind" $kind "context" $) | nindent 8 }}
        - name: homepage-config
          configMap:
            name: {{ include "common.names.name" ( dict "service" $service "kind" $kind ) | quote }}
{{- end }}
