{{- if .Values.services.homepage.enabled }}
{{- $service := .Values.services.homepage -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
  annotations:
    kubernetes.io/service-account.name: {{ $service.name }}
{{- end }}
