{{- if .Values.services.homepage.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.services.homepage.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.homepage.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.services.homepage.name }}
{{- end }}
