{{- if .Values.services.homepage.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.homepage.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.homepage.name }}
secrets:
  - name: {{ .Values.services.homepage.name }}
{{- end }}
