{{- if .Values.services.homepage.enabled }}
{{- $service := .Values.services.homepage -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
    {{- include "homeserver.labels" . | indent 2 }}
    homeserver/vpn: {{ $service.vpn.enabled | default false | ternary "true" "false" | quote }}
secrets:
  - name: {{ $service.name }}
{{- end }}
