{{- if .Values.services.stirlingpdf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.stirlingpdf.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.stirlingpdf.name }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.services.stirlingpdf.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.services.stirlingpdf.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.services.stirlingpdf.name }}
    spec:
      # unfortunately the image needs root access
      # in order to install packages and create a few root directories
      securityContext:
        runAsNonRoot: false
      initContainers:
      {{- if .Values.services.stirlingpdf.vpn.enabled }}
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-conf-secret
                optional: false
          env:
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: "127.0.0.1:9998"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: HEALTH_SERVER_ADDRESS
              value: "127.0.0.1:9999"
            - name: HEALTH_VPN_DURATION_INITIAL
              value: {{ .Values.vpn.health.durationInitial | quote }}
            - name: HEALTH_VPN_DURATION_ADDITION
              value: {{ .Values.vpn.health.durationAddition | quote }}
            - name: HEALTH_SUCCESS_WAIT_DURATION
              value: {{ .Values.vpn.health.successWaitDuration | quote }}
            - name: HEALTH_TARGET_ADDRESS
              value: {{ .Values.vpn.health.targetAddress | quote }}
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 6
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
      {{- end }}
      containers:
        - name: stirlingpdf
          image: "{{ .Values.services.stirlingpdf.image.repository }}:{{ .Values.services.stirlingpdf.image.tag }}"
          imagePullPolicy: {{ .Values.services.stirlingpdf.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.services.stirlingpdf.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: PUID
              value: {{ required "A valid UID required!" .Values.host.uid | quote }}
            - name: PGID
              value: {{ required "A valid GID required!" .Values.host.gid | quote }}
            - name: TZ
              value: {{ required "A valid timezone required!" .Values.host.tz | quote }}
            - name: LANGS
              value: {{ .Values.services.stirlingpdf.langs | quote }}
            - name: DOCKER_ENABLE_SECURITY
              value: {{ .Values.services.stirlingpdf.enableLogin | quote }}
            - name: SECURITY_ENABLE_LOGIN
              value: {{ .Values.services.stirlingpdf.enableLogin | quote }}
            - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
              value: {{ .Values.services.stirlingpdf.installBookAndAdvancedHtmlOps | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /configs
            - name: logs
              mountPath: /logs
      volumes:
        {{- if .Values.services.stirlingpdf.vpn.enabled }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        {{- end }}
        - name: config
          hostPath:
            path: {{ .Values.services.stirlingpdf.config | quote }}
            type: Directory
        - name: logs
          hostPath:
            path: {{ .Values.services.stirlingpdf.logs | quote }}
            type: Directory
{{- end }}
